//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace world_currency.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("world_currency.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ISO_4217_CurrencyTable&gt;
        ///	&lt;CurrencyBlock&gt;
        ///		&lt;CountryName&gt;AFGHANISTAN&lt;/CountryName&gt;
        ///		&lt;CurrencyName&gt;Afghani&lt;/CurrencyName&gt;
        ///		&lt;Currency3LetterName&gt;AFN&lt;/Currency3LetterName&gt;
        ///		&lt;CurrencyNumber&gt;971&lt;/CurrencyNumber&gt;
        ///		&lt;CurrencyMinorUnits&gt;2&lt;/CurrencyMinorUnits&gt;
        ///		&lt;CurrencySymbol&gt;؋&lt;/CurrencySymbol&gt;
        ///	&lt;/CurrencyBlock&gt;
        ///	&lt;CurrencyBlock&gt;
        ///		&lt;CountryName&gt;ÅLAND ISLANDS&lt;/CountryName&gt;
        ///		&lt;CurrencyName&gt;Euro&lt;/CurrencyName&gt;
        ///		&lt;Currency3LetterName&gt;EUR&lt;/Currency3LetterName&gt;
        ///		&lt;CurrencyNumber&gt;978&lt;/CurrencyNumber&gt;
        ///		&lt;C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ISO_4217 {
            get {
                return ResourceManager.GetString("ISO_4217", resourceCulture);
            }
        }
    }
}
